### ISSUE TITLE
Redux like state management crate?

### ISSUE THREAD

**Issue by polarathene** [ErichDonGubler/not-yet-awesome-rust#5] opened 2018-01-09 01:41 UTC
I've come from a web dev background, while I understand Rust isn't quite there for heavy web dev yet(still seems to be trouble in providing an http server that can upgrade connections to websockets on the same port for example), I really did enjoy how [Redux](https://redux.js.org/) worked.

Rust seems to prefer composition and this is something Redux is all about with it's reducers. Middleware support also made it quite powerful and is great to use with React(bit too big of an ask to see a Rust port). IIRC Redux was touted on release as being quite a small library(around 100 lines of JS), yet was great to work with modern JS(ES6+).

Perhaps it worked so well because of JSON being native to JS(where other languages are not as seamless/enjoyable to use JSON), and that it's a dynamic scripting language(which I guess conflicts with Rust being strongly typed and compiled). In Rust I suppose this would be some sort of combination of nested structs or data structure to support the state tree.

I remembered seeing some implementation attempts back in 2016 but they ran into some roadblocks. It seems someone made some progress [here](https://github.com/rust-redux/rust-redux) with rust-redux, so perhaps it's in a better state now and just needs good middleware(the browser debug tools were pretty good, not sure if they could be used with Rust to do time travel of state).

I found this most useful for state management of UI part of software. As state would change via reducers, binded data would update in React UI without additional work by the developer that other UI frameworks did to connect/bind state to the UI, often causing complications, bugs, debugging woes. Going through an introduction of how Redux works probably explains this better than I can :)

**Comment by ErichDonGubler** [comment] 2018-01-09 15:49
Ordinarily, I'd take for face value that something as recognizable as Redux isn't really present in Rust, but I don't want to make assumptions -- is this specifically for developing a frontend with WASM or `emscripten`? Or were you hoping to reuse Flux architecture concepts for pure state management on something else?

**Comment by rrichardson** [comment] 2018-01-16 20:15
The actual interface of Redux is incredibly simple and very easy to reproduce.  The programming model also seems to lend itself very well to Rust.  The fairly recent addition of the persistent data structures [crate](https://github.com/orium/rpds), specifically the HashTrieMap, would be a great starting point for the data store. 

However, I think the big caveat is that the programming model for Redux requires a bunch of (mutable?) handles into what is effectively a global data store (possibly that persists to disk) . 

The challenge for a Redux API,  (IMO) is coming up with a clean and elegant way for many things to hold mutable references to a thing which keeps re-writing itself internally.  I think it's do-able, but is the effort worth it, and would it make sense to just use something like : `rust-rocksdb` with some sort of subscription scheme built-in.

**Comment by ErichDonGubler** [comment] 2018-02-13 01:34
I going to declare a final comment period on this issue.

Remember that the purpose of this repo is to collect use cases. The details figured here are relevant to that conversation, though I feel that with the information that is here, I can only make a basic entry. This is probably due to my lack of expertise. Can anyone add anything else before we close this? What use cases can be taken away from this? I'm thinking only of UIs, some that's where this state management technique has been used recently.

**Comment by polarathene** [comment] 2018-02-13 05:02
I only have the use case of experience using Redux for frontend UI with React. Another big plus for it was the third party support/community and how well it integrated into React. You also had the tooling for debugging(browser plugins) that allowed you to stop the app, view the state, move back/forward through the state like a timeline or undo/redo, or directly alter the state(where a change can chain other reducers to update state and UI elsewhere).

There are some UI toolkits in Rust that might be able to work with a Rust port. Declarative/composable UIs mix really well with it. I can't say if the experience/preference of it will be the same using it in Rust as it was JS due to language differences.

For WASM I guess it could be nice if it was able to at least use the debug tooling Redux has(or a fork of those plugins). I haven't got much thought for it out of frontend/UI use cases, the benefit is mostly that where and how state was managed was clear, it was structured to the pattern(both in usage and file hierachy) and when something would change the data change/event would flow updating anything else that depended on it and all other UI elements(or non UI logic) that bound to it would just update, you make the one change and don't have to manually tell anything else to update/change to the new value/calculation. That is most useful if you have UI representing the same data in several different ways.

There might be other alternatives to that approach, I just remember it being nicer than mvc and other patterns I was used to in the past.

**Comment by ErichDonGubler** [comment] 2018-02-15 03:50
I've tried to capture what I've taken from this discussion with this PR: https://github.com/ErichDonGubler/not-yet-awesome-rust/pull/35

Feedback, anyone? Now's your chance!

**Comment by ErichDonGubler** [comment] 2018-02-16 15:53
Closing, per final comment period. Like with sibling issue https://github.com/ErichDonGubler/not-yet-awesome-rust/issues/6, feel free to comment here or open another issue if you feel that you still want to voice something.

**Closed by ErichDonGubler** 2018-02-16 15:53 UTC
Labels: final-comment-period, good first issue, help wanted, needs-use-cases
